<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Загрузка-данных" data-toc-modified-id="Загрузка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Загрузка данных</a></span></li><li><span><a href="#Умножение-матриц" data-toc-modified-id="Умножение-матриц-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Умножение матриц</a></span></li><li><span><a href="#Алгоритм-преобразования" data-toc-modified-id="Алгоритм-преобразования-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Алгоритм преобразования</a></span></li><li><span><a href="#Проверка-алгоритма" data-toc-modified-id="Проверка-алгоритма-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Проверка алгоритма</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Защита персональных данных клиентов

Вам нужно защитить данные клиентов страховой компании «Хоть потоп». Разработайте такой метод преобразования данных, чтобы по ним было сложно восстановить персональную информацию. Обоснуйте корректность его работы.

Нужно защитить данные, чтобы при преобразовании качество моделей машинного обучения не ухудшилось. Подбирать наилучшую модель не требуется.


Инструкция по выполнению проекта
Загрузите и изучите данные.
Ответьте на вопрос и обоснуйте решение.
Признаки умножают на обратимую матрицу. Изменится ли качество линейной регрессии? (Её можно обучить заново.)
a. Изменится. Приведите примеры матриц.
b. Не изменится. Укажите, как связаны параметры линейной регрессии в исходной задаче и в преобразованной.
Предложите алгоритм преобразования данных для решения задачи. Обоснуйте, почему качество линейной регрессии не поменяется.
Запрограммируйте этот алгоритм, применив матричные операции. Проверьте, что качество линейной регрессии из sklearn не отличается до и после преобразования. Примените метрику R2.
Описание данных
Набор данных находится в файле /datasets/insurance.csv. Скачать датасет.
Признаки: пол, возраст и зарплата застрахованного, количество членов его семьи.
Целевой признак: количество страховых выплат клиенту за последние 5 лет.

## Загрузка данных

In [14]:
from __future__ import division, print_function
# отключим всякие предупреждения Anaconda
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression 
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score


In [15]:
try:
    data = pd.read_csv('/datasets/insurance.csv')
    
    
except:
    data = pd.read_csv('C:/Users/анатолий/Documents/datasets/insurance.csv')
    

In [16]:
data=data.rename(columns=str.lower)
data[['возраст','зарплата']] = data[['возраст','зарплата']].astype('int64')
display(data.head(15))
data.info()

пол  возраст  зарплата  члены семьи  страховые выплаты
0     1       41     49600            1                  0
1     0       46     38000            1                  1
2     0       29     21000            0                  0
3     0       21     41700            2                  0
4     1       28     26100            0                  0
5     1       43     41000            2                  1
6     1       39     39700            2                  0
7     1       25     38600            4                  0
8     1       36     49700            1                  0
9     1       32     51700            1                  0
10    1       25     36600            1                  0
11    1       38     29300            0                  0
12    0       23     39500            3                  0
13    0       21     55000            0                  0
14    0       40     43700            1                  0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   пол                5000 non-null   int64
 1   возраст            5000 non-null   int64
 2   зарплата           5000 non-null   int64
 3   члены семьи        5000 non-null   int64
 4   страховые выплаты  5000 non-null   int64
dtypes: int64(5)
memory usage: 195.4 KB


In [17]:
data.duplicated().sum() 

153

In [18]:
data.drop_duplicates(inplace=True)
data.duplicated().sum()

0

In [19]:
features = data.drop('страховые выплаты',axis=1)
features.shape

(4847, 4)

In [20]:
target = data['страховые выплаты']
target.shape

(4847,)

In [21]:
X = features.values
X.shape

(4847, 4)

In [22]:
y = target.values
y.shape

(4847,)

Данные готовы к анализу,размерности идентичны,дубликаты удалены.

## Умножение матриц

В этом задании вы можете записывать формулы в *Jupyter Notebook.*

Чтобы записать формулу внутри текста, окружите её символами доллара \\$; если снаружи —  двойными символами \\$\\$. Эти формулы записываются на языке вёрстки *LaTeX.* 

Для примера мы записали формулы линейной регрессии. Можете их скопировать и отредактировать, чтобы решить задачу.

Работать в *LaTeX* необязательно.

Обозначения:

- $X$ — матрица признаков (нулевой столбец состоит из единиц)

- $y$ — вектор целевого признака

- $P$ — матрица, на которую умножаются признаки

- $w$ — вектор весов линейной регрессии (нулевой элемент равен сдвигу)

Предсказания:

$$
a = Xw
$$

Задача обучения:

$$
w = \arg\min_w MSE(Xw, y)
$$

Формула обучения:

$$
w = (X^T X)^{-1} X^T y
$$

Итак 
докажем,что предсказание на исходных признаках $a=Xw$ равно предсказанию на преобразованных признаках $a_1=X_1w_1$,где $X_1=XP$ ($P$ - матрица шифрования).

Формула обучения для новой матрицы

 $w_1 = ((X_1)^T X_1)^{-1}(X_1)^T y= ((XP)^T XP)^{-1}(XP)^T y = (P^T X^T XP)^{-1} P^T X^T y$ получена после преобразований с учетом свойств транспонированных и единичных матриц,указанных ниже в проекте.

Тогда предсказание на преобразованных признаках равно

 $a_1=XP(P^T X^T XP)^{-1} P^T X^T y$
       
Вспомним шестое свойство линейного пространства A(BX)=(AB)X получим следующее выражение:

   $a_1=XPP^{-1}(P^TX^TX)^{-1}P^TX^Ty$ и в этом выражении видим единичные матрицы
   
   $PP^{-1}$ и $(P^T)^{-1}P^T$
   
Таким образом получим в итоге

   $a_1=X(X^TX)^{-1}X^Ty=Xw$ _  ч.т.д.



Несколько определений и правил действий с матрицами

1. Умножить матрицу А справа на матрицу В можно только тогда когда число столбцов матрицы А совпадает с числом строк матрицы В
2. Единичная матрица Е это та у которой по главной диагонали стоят единицы,она квадратная порядка n и ее свойства:
   ЕА = А для любой матрицы А с n-количеством строк
   АЕ = А для любой матрицы А с n-количеством столбцов.
3. Транспонированной матрицей А^Т к матрице А является та,у которой каждый столбец это строка матрицы А и ее свойства:
    (А^T)^T = A
    (A+-B)^T = A^T +- B^T
    (AB)^T = B^T A^T     
4. Определитель матрицы det A (для n=2) есть разность произведений элементов матрицы  a(1,1)*a(2,2)-a(2,1)*a(1,2) и у него много разных свойств (они для нашей задачи не очень важны)
5. Обратной матрицей к квадратной матрице А является такая,что 
    A^-1 A = AA^-1 = E 
6. Линейное(векторное) пространство это любое множество на котором выполняются операции умножения на действительное число и сложения,удовлетворяющие свойствам ассоциативности,коммутативности,существованию нулевого и противоположного вектора и двум свойствам дистрибутивности.
7. Базис - любая максимально линейно независимая система векторов (возможность представления векторов и в другом базисном пространстве используя координаты векторов).
8. Собственные значения оператора - числа на главной диагонали матрицы перехода с одного базиса в другой.
9. Евклидово пространство - все операции как и в линейном пространстве плюс еще скалярное произведение векторов,что позволяет использовать длины векторов и углы между векторами.



## Алгоритм преобразования

**Алгоритм**

Алгоритм преобразования таков - умножим матрицу обучающих признаков на случайную обратимую матрицу P размером 4х4. Создадим модель линейной регрессии и обучим ее до преобразования и посчитаем метрику R2. После умножения исходных признаков на невырожденную матрицу соответствующего размера и вновь посчитаем метрику R2. Метрики R2  должны быть равными.

**Обоснование**

Все операции с матрицами в sklearn производятся в евклидовом пространсте - можем вектора умножать на число,суммировать,перемножать скалярно(получая в итоге этого вектор),и все то что написано выше в свойствах линейного пространства.Поэтому умножая матрицу на другую, но невырожденную матрицу нужной размерности мы в итоге получим те же вектора-признаки,что и в исходной матрице,но с другими значениями можно сказать модулей.
Т.е. эти вектора будут по сути коллениарными между собой(до преобразования и после него) что и позволяет использовать такой подход для решения задачи проекта.

## Проверка алгоритма

In [23]:
model =  LinearRegression()
model.fit(features,target)
R2 = cross_val_score(model,features,target,scoring='r2',cv=5)
print('Значение R2 на основном массиве :', R2.mean().round(5))

Значение R2 на основном массиве : 0.42779


Создадим матрицу нормально распределенных случайных значений размером 4х4 

In [24]:
det = 0 
while det == 0:
    P = np.random.normal(size=(4, 4))
    det = np.linalg.det(P)
P

array([[ 0.24114045,  1.00916635,  0.74863872, -1.40689867],
       [-0.98863669, -1.07482417, -0.04220679,  1.0697192 ],
       [-1.71079343,  0.25073536, -0.2309044 ,  0.17776637],
       [-0.44904379,  2.57122624,  0.42722354,  0.56309566]])

Проверим что получилось

In [25]:
a=X@P
print(a)
a.shape

[[-84896.09636869  12395.98658715 -11453.41275894   8860.22653377]
 [-65056.07685004   9481.07309365  -8775.88141437   6804.89216039]
 [-35955.33259265   5234.27271391  -4850.21635579   3764.11558344]
 ...
 [-58016.5682577    8483.57476161  -7827.64878227   6048.80044832]
 [-55965.80131277   8184.12307072  -7549.47205595   5836.7764422 ]
 [-69486.10317945  10153.34103786  -9374.7244883    7246.42287276]]


(4847, 4)

Получилось хорошо - матрица необходимой размерности 
Вычислим метрику уже для этой зашифрованной матрицы

In [26]:
model_cript1 =  LinearRegression()
model_cript1.fit(a,y)
R2 = cross_val_score(model_cript1,a,y,scoring='r2',cv=5)
print('Значение R2 на зашифрованном массиве :', R2.mean().round(5))

Значение R2 на зашифрованном массиве : 0.42779


Значения метрик R2 до и после шифрования равны - ч.т.д.